/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatBubbleSelector: typeof import('./src/components/ChatBubbleSelector.vue')['default']
    CoinLayer: typeof import('./src/components/CoinLayer.vue')['default']
    DealingLayer: typeof import('./src/components/DealingLayer.vue')['default']
    GlobalLoading: typeof import('./src/components/GlobalLoading.vue')['default']
    PlayerSeat: typeof import('./src/components/PlayerSeat.vue')['default']
    PokerCard: typeof import('./src/components/PokerCard.vue')['default']
    ReconnectDialog: typeof import('./src/components/ReconnectDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
