/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatBubbleSelector: typeof import('./src/components/ChatBubbleSelector.vue')['default']
    CoinLayer: typeof import('./src/components/CoinLayer.vue')['default']
    DealingLayer: typeof import('./src/components/DealingLayer.vue')['default']
    GlobalLoading: typeof import('./src/components/GlobalLoading.vue')['default']
    HelpModal: typeof import('./src/components/HelpModal.vue')['default']
    HistoryModal: typeof import('./src/components/HistoryModal.vue')['default']
    PlayerSeat: typeof import('./src/components/PlayerSeat.vue')['default']
    PokerCard: typeof import('./src/components/PokerCard.vue')['default']
    ReconnectDialog: typeof import('./src/components/ReconnectDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
  }
}
